"""Explicit dependency contract for the workspace web-runtime namespace.

Code version: v1.0.0
"""

from __future__ import annotations

from types import SimpleNamespace


# The workspace renderer and its four request, history, finalize, and response
# modules share one namespace. This tuple is that namespace's explicit
# contract: exactly the runtime names those modules read, and nothing else.
# `tests/test_runtime_workspace_dependencies.py` rejects both an undeclared
# dependency and a declared name no module still uses, so the previous
# `SimpleNamespace(**context)` blanket cannot silently return.
WORKSPACE_RUNTIME_DEPENDENCIES: tuple[str, ...] = (
    "Any",
    "BACKTEST_VIEWS",
    "BASE_CURRENCY",
    "BASE_TIMEZONE",
    "CODE_VERSION",
    "COMPARE_INTRADAY_PERIODS",
    "COMPARE_PERIODS_1D",
    "DEFAULT_INTERVAL",
    "DEFAULT_PERIOD",
    "DEFAULT_TICKERS",
    "FETCH_ABORT_DEBUG_CONFIG",
    "HTML_LANG_BY_LANGUAGE",
    "LANGUAGE_LABELS",
    "LOCAL_STORE_PAGE_SIZE",
    "LOGGER",
    "MIN_TICKERS",
    "MissingComparisonMarketDataError",
    "PERIOD_DAY_SPANS",
    "PERIOD_LABELS",
    "PERIOD_MONTH_SPANS",
    "PERIOD_OFFSETS",
    "PROJECT_DISPLAY_URL",
    "PROJECT_SOURCE_URL",
    "QuoteProfile",
    "SETTINGS_FEEDBACK_COOKIE",
    "SETTINGS_LANGUAGE_PAGE_SIZE",
    "SUPPORTED_LANGUAGE_CODES",
    "SUPPORTED_PERIODS_1D",
    "SUPPORTED_PERIODS_1M",
    "SeriesPayload",
    "_cached_backtest",
    "_get_backtest_cache_key",
    "_read_settings_feedback",
    "_run_backtest_from_request",
    "_run_dca_from_request",
    "_strategy_supported_execution_intervals",
    "align_datasets_on_common_dates",
    "align_intraday_datasets_for_compare",
    "app_meta",
    "append_live_compare_intraday_dataset",
    "apply_no_store_headers",
    "base_labels",
    "best_numeric_metric",
    "build_benchmark_series_payloads",
    "build_color_token_rows",
    "build_compare_series_payload",
    "build_current_compare_one_day_datasets",
    "build_date_constraint_payload",
    "build_default_weights",
    "build_empty_compare_axis_dataset",
    "build_export_image_rows",
    "build_font_token_rows",
    "build_local_market_rows_for_tickers",
    "build_local_store_page_url",
    "build_local_store_pagination_items",
    "build_market_cap_series_payload",
    "build_material_token_rows",
    "build_network_service_rows",
    "build_one_day_intraday_date_constraint_payload",
    "build_portfolio_growth_multipliers",
    "build_portfolio_series_payload",
    "build_portfolio_series_payload_for_shares",
    "build_series_colors",
    "build_settings_url",
    "build_short_intraday_date_constraint_payload",
    "build_strategy_form_fields",
    "build_strategy_form_sections",
    "build_strategy_option_groups",
    "build_strategy_settings_groups",
    "build_style_token_rows",
    "build_supported_compare_periods",
    "build_supported_periods_for_history_store",
    "build_supported_periods_from_dates",
    "build_trade_url",
    "build_translation_map",
    "build_ttm_dividend_yield_map",
    "build_view_url",
    "canonical_compare_overnight_ticker",
    "canonicalize_money_market_ticker",
    "chart_config",
    "collect_strategy_form_values",
    "configured_money_market_quote_currencies",
    "defaults",
    "ensure_latest_backtest_caches",
    "ensure_latest_daily_caches",
    "ensure_positive_portfolio_weights",
    "exact_trading_dates_in_range",
    "extract_stock_split_events",
    "extract_union_dates",
    "fetch_history",
    "fetch_quote_profile",
    "format_compare_intraday_market_local_display_range",
    "format_display_date",
    "format_period_label",
    "get_strategy_ticker_contract",
    "has_compare_overnight_market_data_source",
    "has_remote_market_access",
    "hex_to_rgba",
    "history_store_path_for",
    "infer_ticker_market",
    "instantiate_strategy",
    "is_market_regular_session_active_for_ticker",
    "is_price_field_strategy",
    "list_enabled_strategies",
    "list_local_market_tickers",
    "load_backtest_execution_mode",
    "load_broker_settings",
    "load_cash_equivalent_tickers",
    "load_compare_one_day_intraday_dataset",
    "load_date_display_settings",
    "load_investment_cost_basis_method",
    "load_language_settings",
    "load_longbridge_account_label",
    "load_smtp_settings",
    "local_store_page_value",
    "logos",
    "make_response",
    "market_timezone_for_ticker",
    "market_trading_date_for_timestamp",
    "market_trading_dates_for_history",
    "max_tickers_for_view",
    "modal_banner_icon_class",
    "money_market_settings",
    "normalize_portfolio_share_weights",
    "normalize_portfolio_weights",
    "normalize_settings_section",
    "normalize_ticker_input",
    "normalize_trade_section",
    "parse_bool_flag",
    "parse_float_value",
    "parse_int_value",
    "parse_portfolio_allocation_mode",
    "parse_range_request_args",
    "parse_requested_shares",
    "parse_requested_tickers",
    "parse_requested_weights",
    "pd",
    "prepare_intraday_dataset_for_compare",
    "quote_profile_to_json",
    "record_strategy_usage",
    "record_ticker_usage",
    "render_template",
    "request",
    "resolve_backtest_tickers",
    "resolve_compare_overnight_tickers",
    "resolve_comparison_metric",
    "resolve_effective_period_for_many",
    "resolve_known_ticker_company_name",
    "resolve_requested_period_from_supported",
    "resolve_settings_tab",
    "resolve_stored_logo_url",
    "resolve_workspace_dividend_mode",
    "sanitize_broker_settings_for_view",
    "sanitize_smtp_settings_for_view",
    "select_price_series",
    "settings_page_value",
    "should_use_modal_banner_message",
    "simulate_recurring_investment",
    "slice_dataset_for_period",
    "slice_dataset_to_exact_range",
    "slice_datasets_for_compare_period",
    "slice_datasets_to_exact_range",
    "slice_intraday_dataset_to_trading_dates",
    "slice_intraday_datasets_for_compare_period",
    "supports_compare_extended_hours",
    "supports_compare_overnight",
    "theme",
    "theme_dark",
    "theme_light",
    "translate_labels",
    "translate_nested_text",
    "translate_text",
    "truncate_intraday_datasets_to_common_live_timestamp",
    "validate_ticker_or_raise",
)


def build_workspace_dependencies(context: dict[str, object]) -> SimpleNamespace:
    """Return only the declared runtime names the workspace modules consume."""
    missing = [name for name in WORKSPACE_RUNTIME_DEPENDENCIES if name not in context]
    if missing:
        raise KeyError(
            "Missing workspace runtime dependencies: " + ", ".join(sorted(missing))
        )
    return SimpleNamespace(
        **{name: context[name] for name in WORKSPACE_RUNTIME_DEPENDENCIES}
    )
